### ISSUE TITLE
Modifikation Lebensbalken

### ISSUE THREAD

**Issue by kaeptnahab** [krrrcks/krrrcks-mudlet#1]
Ich habe mal den Lebensbalken modifiziert, so dass er jetzt den Spielernamen und dessen Level mit anzeigt. Zusätzlich zu registrierende Events: gmcp.MG.char.base und gmcp.MG.char.info.

``` LUA
function zeigeVitaldaten()
  setGauge("lpbalken", gmcp.MG.char.vitals.hp, gmcp.MG.char.maxvitals.max_hp, 
    ""..gmcp.MG.char.base.name.." ["..gmcp.MG.char.info.level.."]  "..gmcp.MG.char.vitals.hp .. "/" ..gmcp.MG.char.maxvitals.max_hp.."")
  setGauge("kpbalken", gmcp.MG.char.vitals.sp, gmcp.MG.char.maxvitals.max_sp, 
    ""..gmcp.MG.char.vitals.sp .. "/" ..gmcp.MG.char.maxvitals.max_sp.."")
end
```

**Comment by krrrcks** [comment]
Ich habe die Anregung in die Statusleiste mit aufgenommen.

**Comment by Kebap** [comment]
Dies führt zu Problemen, wenn der Spielername sehr lang ist. Die Anzeige der Lebenspunkte passt dann nicht mehr vollständig in den Balken. Besser wäre ein eigener Balken für Name und Stufe, während die Lebenspunkte wie Konzentrationspunkte allein angezeigt werden.

**Comment by krrrcks** [comment]
Ja, das stimmt. Ist mir bei laengeren Namen auch schon mal aufgefallen; ich finde auch die Kontraste der Standardfarben nur bedingt super. ... Ich mach das Issue mal wieder auf.

**Comment by Kebap** [comment]
Neue GUI löst diese Probleme: https://github.com/Kebap/krrrcks-mudlet

**Comment by krrrcks** [comment]
Fein, habe es bei mir übernommen.
